name: Terraform

on:
  push:
    paths:
      - 'terraform/**'

jobs:

  terraform:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - uses: hashicorp/setup-terraform@v3

    - uses: aws-actions/configure-aws-credentials@v4
      with:

        aws-access-key-id:
          ${{ secrets.AWS_ACCESS_KEY_ID }}

        aws-secret-access-key:
          ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        aws-region:
          ${{ secrets.AWS_REGION }}

    - run: terraform init

    - run: terraform validate

    - run: terraform plan

    - run: terraform apply -auto-approve